luavela/luavela

- .gitattributes
This change fixes GitHub language stats. Instead of this:
We get this (see https://github.com/eliasdaler/luavela):
lua-Harness stores a lot of HTML files and .gitattributes allows us to ignore them.
Note that this change takes ~3-4 days to be applied to stats, so merging this PR won't give immediate result.
> Exclude lua-Harness HTML files which skew repo language stats

- ChangeLog
- docs/public/pub-running-ujit.rst
- src/jit/lj_jit.h
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/apart-scalar.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/apart.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/fload-meta-guard.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/gset.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/hpart-newref-meta-guard.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/hpart-newref.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/hpart-no-newref-hoisting.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/hpart-no-newref-partial.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/hpart-no-newref.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/in-place.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/load-used-by-assert.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/load-used-by-bc-isf.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/load-used-by-bc-ist.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/load-used-by-bc-not.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/no-fuse-meta-dst.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/no-fuse-meta-src.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/pri-nil-empty.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/pri-nil-non-empty.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/pri-non-nil.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/same-table-diff-keys.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/same-table-same-key.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/sload-meta-guard.lua
- tests/impl/uJIT-tests-Lua/suite/chunks/movtv/tvload-meta-guard.lua
Unfortunately, it turned out that `movtv` and `motvpri` are not yet stable and cause crashes in some conditions, so they should be excluded from -O4 set of optimizations and are marked as WIP.
> Exclude movtv and movtvpri from -O4

- ChangeLog
- src/jit/lj_ffrecord.c
- tests/impl/uJIT-tests-Lua/suite/chunks/string/find-fold-bug.lua
- tests/impl/uJIT-tests-Lua/suite/string.t
This is a squashed changeset of the following commits from
tarantool/luajit repo:
* [587532e](https://github.com/tarantool/luajit/commit/587532e66ab447728be8a0a23fd8a3ef4f623661)
* [98b1cfc](https://github.com/tarantool/luajit/commit/98b1cfcc00f49d7c55e97c4aab57ab7c5aa7799a)
Relates to [LuaJIT gh-505](https://github.com/LuaJIT/LuaJIT/issues/505)
> Backported fix for string.find recording

- .travis.yml
- .travis/install.sh
- ChangeLog
Tested against (almost) the same configurations as in `INSTALL.rst`, namely
* macOS 10.13, AppleClang 10.0.0
* macOS 10.14, AppleClang 10.0.1
* macOS 10.14, AppleClang 11.0.0
Unfortunately, Travis doesn't support macOS 10.15 for now. However, I've added a job with the same version of AppleClang that was used on macOS 10.15 when preparing https://github.com/iponweb/luavela/pull/23 - AppleClang 11.0.0.
Also, each job now additionally runs the smoke tests.
> macOS support in CI builds

- ChangeLog
- README.rst
- etc/ujit.1
- etc/ujit.pc.in
- src/ujit.h.in
- tests/impl/uJIT-tests-C/suite/test_lua_yield.c
- tests/impl/uJIT-tests-Lua/suite/chunks/profile-leaf/profile_aux.lua
- tests/lang/lua-Harness/suite/docs/index.md
Does what it says on the box: the badge is green now.
Additionally, all the links that were pointing to the old  `iponweb/luavela` repo were updated with `luavela/luavela`.
> Fix the Travis CI status badge URL

- tools/parse_profile/ujpp_demangle.h
The removed variable is excess. Besides it's declared in header file and
breaks uJIT build on GCC 10 with multiple definition error.
Fixes #33
> Remove unused variable

- .gitattributes
.gitattribute parsing rules have been changed in rugged[1] between v0.28.5 and v1.0.0 (I believe something changed in libgit2, but it requires a bit more time to found the particular revision and I also guess it is required only for the history, so I gave up). As a result linguist[2] fails to find all files to be suppressed that are specified via the pattern in .gitattributes entry. Several users have been also experienced the same effect (for more info see github/linguist#5439 and github/linguist#5451).
The fix itself is quite trivial: to suppress the files located not only in the specified directory, but also all in its subdirectories, double asterisk glob has to be used.
[1]: https://github.com/libgit2/rugged
[2]: https://github.com/github/linguist
Signed-off-by: Igor Munkin …
> Fix lua-Harness .gitattribute entry

- .github/workflows/lint.yml
- tools/ujit-gdb.py
This patchset is a follow up for #40 and introduces GitHub Actions for all linter checks available in LuaVela repository. However, while testing the workflow flake8 found the error in `tools/ujit-gdb.py` script that is fixed by the first patch.
The second commit adds GitHub Action workflow for Clang Tidy, Clang Format, Luacheck and Flake8 to be run on Ubuntu 20.04 due to the verified list of the dependencies.
> Introduce GitHub Actions for linter checks

- src/lj_tab.c
- tests/impl/uJIT-tests-Lua/suite/chunks/table/toset/mutated.lua
Before the patch `lj_tab_toset` uses `lj_tab_newkey` helper to insert the new key into resulting set. As a result, the new slot in GCtab object is allocated unconditionally (i.e. without the check whether the given key is already stored in this table) causing key duplication in the resulting table violating "set" definition.
Within the patch `lj_tab_newkey` is replaced with `lj_tab_set` helper, that yields the existing slot if the given key is stored in the table, or allocate the new slot otherwise.
Fixes #38
> Fix key duplication in lj_tab_toset

- .github/actions/setup-macos/README.md
- .github/actions/setup-macos/action.yml
- .github/workflows/testing.yml
- src/lib/ujit.c
The first commit extends GitHub Actions workflow matrix to test LuaVela on macOS (macOS Big Sur in particular) against different build types (i.e. Debug and Release). LuaVela is built only via the default compiler (AppleClang) with only static libujit to be used in LuaVela binary built for tests.
There is also GitHub Action for macOS environment setup introduced in scope of this commit. However, it looks like all requirements have already been pre-installed on GitHub hosted public macOS runners, so there is no need to install extra tools within the new GitHub Action.
The second commit fixes profile ID buffer overflow, that was found by quite strict AppleClang compiler configuration (-Werror, -Wfortify-source).
> Introduce GitHub Actions on macOS

- tests/impl/uJIT-tests-C/suite/test_lua_iprof.c
After enabling GitHub Actions to run all uJIT tests by the commit cd557a9 ("Enable GitHub Actions for testing LuaVela on Linux"), `iprof` tests fails from time to time. As a result of the investigation it was found that only the tests simulating real coroutine switches are affected. Since there is no way to tweak CI public runners provided by GitHub, we can't rely on the environment and have to mock time-related interfaces used in the aforementioned tests.
To reduce the dependency on the system clock, two libc functions are overridden in scope of this patch:
* `sleep(3)`: simply increments second counter stored in the clock mock by the given amount of seconds.
* `clock_gettime(3)`: increments nanosecond counter stored in the clock mock by the JIFFY value (i.e. 1 ns), normalizes the …
> Fix flaky tests for instrumenting profiler

- scripts/depends-test-20-04
- scripts/run-clang-tidy
- src/jit/lj_asm_x86.h
- tests/impl/uJIT-tests-C/suite/test_cci_immutable.c
- tests/impl/uJIT-tests-C/suite/test_str.c
Clang Tidy is upgraded up to version 11.0.0 to make seamless migration from Ubuntu 20.04 to Ubuntu 22.04 (both distros provide the mentioned version of Clang toolchain from the default repositories). Further Clang toolchain upgrades will be completed after full migration to Ubuntu 22.04.
It's not quite easy to properly fix all the issues reported by Clang Tidy, so some of them are filed as a tickets in the GitHub queue and temporarily suppressed in `run-clang-tidy` runner.
> Update Clang Tidy version

- cmake/toolchain/Clang.cmake
- src/utils/lj_alloc.c
- src/utils/random.c
- src/utils/random.h
- tests/impl/uJIT-tests-C/suite/test_common.h
- tests/impl/uJIT-tests-C/suite/test_common_lua.h
- tests/impl/uJIT-tests-C/suite/test_cstr.c
I tried to build uJIT on Ubuntu Noble Numbat (development branch) Docker image. The diff I made for build and test requirements are below:
```diff
diff --git a/cmake/toolchain/Clang.cmake b/cmake/toolchain/Clang.cmake
index c5fcb28..82fb2eb 100644
--- a/cmake/toolchain/Clang.cmake
+++ b/cmake/toolchain/Clang.cmake
@@ -5,7 +5,7 @@
-set(CMAKE_C_COMPILER "clang-6.0")
+set(CMAKE_C_COMPILER "clang-18")
diff --git a/scripts/depends-build-20-04 b/scripts/depends-build-20-04
index 2850d4b..3008a0e 100644
--- a/scripts/depends-build-20-04
+++ b/scripts/depends-build-20-04
@@ -1,9 +1,9 @@
autoconf
-clang-6.0
+clang-18
cmake
gcc
-gcc-8=8.4.0-*
+gcc-13
libc6-dev
-libstdc++-8-dev
+libstdc++-10-dev
libstdc++6
libtool
diff --git a/scripts/depends-test-20-04 b/scripts/depends-test-20-04
index …
```
> Fix build for Ubuntu 24.04 toolchain

- .clang-format
- scripts/depends-test-20-04
- scripts/run-clang-format
- src/dump/uj_dump_datadef.c
- src/dump/uj_dump_datadef_regs_x86.h
- src/dump/uj_dump_progress.c
- src/dump/uj_dump_stack.c
- src/jit/emit/uj_emit_ct.c
- src/jit/uj_record_indexed.c
- src/profile/uj_iprof.c
- src/uj_capi.c
- src/uj_dwarf.c
- src/uj_gdbjit.c
- src/uj_lib.c
- src/uj_sigtimer.c
- src/uj_state.c
- src/uj_str.c
- src/utils/strhash/city.c
- tools/parse_profile/ujpp_table.c
Clang Format is upgraded up to version 11.0.0 to make seamless migration from Ubuntu 20.04 to Ubuntu 22.04 (both distros provide the mentioned version of Clang toolchain from the default repositories). Further Clang toolchain upgrades will be completed after full migration to Ubuntu 22.04.
---
Within the first patch, the current chosen formatting policy for `BreakBeforeTernaryOperators` (i.e. `false`) is broken since Clang Format 11.0.0, causing a misindent for the sources following the line break. What's even more upsetting is that this misindent is fixed only in Clang Format 14.0.0. So, this bug makes us to reformat all the ternary operators now, and revert this change after upgrading Clang toolchain to 14.0.0.
I believe, that the chosen policy is not widely used, otherwise it would not …
> Update Clang Format version

- cmake/toolchain/Clang.cmake
- scripts/depends-build-20-04
Clang is upgraded up to version 11.0.0 to make seamless migration from Ubuntu 20.04 to Ubuntu 22.04 (both distros provide the mentioned version of Clang toolchain from the default repositories).
Further Clang toolchain upgrades will be completed after full migration to Ubuntu 22.04.
> Update Clang version

- .github/workflows/testing.yml
GitHub announced[1] that macos-11 has been deprecated and will no longer be available after 28.06.2024, so macos-12 will be used in uJIT CI as a result of the patch. There is also macos-13 runners provided by GitHub, but it uses Clang 15 compiler toolchain (AppleClang 15 to be precise), that requires another try to make a proper fix for all the spots where diagnostics has been suppressed in #63. Furthermore, it was found, that there is no bootstrap routine for macOS pipeline, hence, using the most suitable available version for now is OK (though, macOS pipeline should be refined later).
[1]: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> Upgrade to macOS 12 in GitHub Actions

- .github/bootstrap/build-depends-22-04
- .github/bootstrap/test-depends-22-04
- .github/workflows/linux.yml
This patch extends the set of the supported platforms by Ubuntu 22.04 (Jammy Jellyfish). Fortunately, all the packages from the dependency list are the same except the GCC toolchain.
> Add Ubuntu 22.04 to GitHub Actions

- src/vm_x86.dasc
When comparing GC objects payload (i.e. their `GCobj` pointers) in scope of `BC_ISEQV`/`BC_ISNEV` bytecodes, both values are loaded into the 64-bit registers, but only lower 32 bits are compared later. Hence, there might be the address parts clashing, leading to invalid comparison results, when the LSBs are the same, but the MSBs are not.
This register mischoice was introduced in the very first uJIT commit, since VM code had been taken intact from vanilla LuaJIT sources, but 128-bit TValue (and, ergo, 64-bit `GCobj` pointers) are uJIT specifics. So, this is likely a typo, undetected since 2015.
As a result of the patch, 64-bit registers are used in this `<cmp>` instruction. Unfortunately, I have no reproducer for this, so I can't provide a proper test for this changeset.
> Fix GCobj pointer comparison in BC_ISEQV/BC_ISNEV

- src/jit/lj_ffrecord.c
- src/jit/lj_record.c
- tests/impl/uJIT-tests-Lua/suite/chunks/table/rindex/tailcall.lua
- tests/impl/uJIT-tests-Lua/suite/table.t
Hi LuaVela team,
There are some problems with recording tail-called `rindex()`:
1. Since return type checks are emitted after `CALLT` (or `CALLMT`) recording, `RETF` instruction will be emitted before them:
```
0024 rax      p64 CALLL  lj_tab_rawrindex_jit  (0023)
0025       >  p32 RETF   tailcall.lua:7  [0x7fa5168ad168]
0026       >  p64 NE     0024  [NULL]
0027 rax   >  str TVLOAD 0024
```
Which leads to situation when frame pointer will be unwinded to caller, but then trace exits due to failed return type check and starts executing calle's PC.
Just to compare, this is IR with regular return (`RETF` is placed after checks):
```
0024 rax      p64 CALLL  lj_tab_rawrindex_jit  (0023)
0025       >  p64 NE     0024  [NULL]
0026 rax   >  str TVLOAD 0024
....              SNAP   #1   [ ---- …
```
> Fix rindex tail call recording

- .github/workflows/macos.yml
- cmake/toolchain/MacOS.cmake
GitHub announced in https://github.com/actions/runner-images/issues/10721 that `macos-12` has been deprecated and will no longer be available after 03.12.2024, so `macos-13` will be used in uJIT CI as a result of the patchset. The first patch also introduces the new CMake toolchain file with a tiny tweak (and a huge reasoning for it) to make AppleClang happy on `macOS-13` (see more details in #63).
Follows up #63
> Upgrade to macOS 13 in GitHub Actions

- scripts/bump.sh
Finally decided to share my auxiliary script for bumping copyright year to the public domain: maybe someone would like to replace me in this annual maintenance, or even setup a scheduled CI pipeline for the next year. `bump.sh` is pretty simple: if one runs the script, all flowerboxes will be adjusted and the changes will be committed to the current working branch. At the same time, `bump.sh` is quite Gentoo-ish: it provides `-p` (`p` is for pretend) flag, so the flowerboxes are adjusted, but the changes are not committed (only staged). Enjoy!
> Introduce bump.sh

- src/lj_tab.c
- tests/impl/uJIT-tests-Lua/suite/chunks/ffi/gcfin_table_reallocation.lua
- tests/impl/uJIT-tests-Lua/suite/ffi.t
LuaVela has the internal weak table to keep the mapping for GCcdata objects to their finalizers, which are set via `ffi.gc`. When GCcdata object becomes dead, there is still the key in this weak table until it's finalized by the Lua garbage collector (more precisely, until the next GCfinalize phase). When the table reallocation occurs, these keys are copied intact to the new hash part.
LuaVela uses `copyTV` for such move, but there is just a plain pointer assignment in LuaJIT. As a result, the assertion within `tvchecklive` (to be more precisely within `isdead` check) hits.
This patch replaces `copyTV` with the simple pointer move.
Relates to tarantool/tarantool#5101
Co-authored-by: Igor Munkin <imun@cpan.org>
> Fix moving dead slots in FFI finalizers table

- 3rdparty/CMakeLists.txt
- CMakeLists.txt
- cmake/ClangTidy.cmake
- cmake/MakeSourceList.cmake
- etc/CMakeLists.txt
- src/CMakeLists.txt
- tests/CMakeLists.txt
- tools/CMakeLists.txt
According to the docs[1], compatibility with versions of CMake older than 3.5 is deprecated since the version 3.27. Ubuntu 24.04 provides CMake 3.28.3 by default, so uJIT configuration starts spoiling the diagnostics with the following warning:
```
CMake Deprecation Warning at CMakeLists.txt:11 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```
Since there is no particular policies specified in the project CMake machinery, there is no need to stick to the 3.3.2 version. However, migration to the newest version requires more precise changes, so this patch only bumps the minimal required …
> Bump CMake minimal version up to 3.5

- cmake/toolchain/MacOS.cmake
To make the patch, committed in 5133b1d10be23c83caaa5830aaf01cb697c5b438 ("Bump copyright date"), `bump.sh` has been run on the outdated local master branch (i.e. the commit b17c2b69e99d63fa4315167b42edf7ba9a2c1e41 ("Introduce macOS toolchain setup for CMake") has not been pulled from the upstream). Hence, the flowerbox in the introduced CMake file has not been touched by the script.
This patch updates the year in the aforementioned flowerbox via `bump.sh`.
Follows up #73
> Bump missing copyright date
